# Generated by Django 2.2.5 on 2019-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingshan', '0003_auto_20191030_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='DISTRICT_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
