# Generated by Django 2.2.6 on 2019-10-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20191024_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dic',
            name='REPORT_NUM',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
