# Generated by Django 2.2.6 on 2019-10-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20191024_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
