# Generated by Django 2.2.6 on 2019-10-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_auto_20191025_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='REPORT_NUM',
            field=models.IntegerField(default=0),
        ),
    ]
