# Generated by Django 2.2.6 on 2019-10-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0010_auto_20191025_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
