# Generated by Django 2.2.6 on 2019-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0011_test_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='num',
            field=models.CharField(max_length=20),
        ),
    ]
