# Generated by Django 2.2.6 on 2019-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0013_auto_20191026_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='numm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='num',
            field=models.CharField(max_length=200),
        ),
    ]
