# Generated by Django 2.2.6 on 2019-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0016_remove_test_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
