# Generated by Django 2.2.6 on 2019-10-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0017_auto_20191026_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='num',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
    ]
