# Generated by Django 2.2.6 on 2019-10-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0020_test_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
