# Generated by Django 2.2.6 on 2019-10-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0021_auto_20191026_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='age',
            new_name='testnum',
        ),
    ]
