# Generated by Django 2.2.6 on 2019-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0022_auto_20191026_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='testtime',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
