# Generated by Django 2.2.6 on 2019-10-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0024_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dic',
            name='testtime',
        ),
    ]
