# Generated by Django 2.2.6 on 2019-10-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0026_dic_testtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user1',
        ),
    ]
