# Generated by Django 2.2.6 on 2019-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0027_auto_20191026_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='CREATE_TIME',
            field=models.DateTimeField(max_length=200),
        ),
    ]
