# Generated by Django 2.2.6 on 2019-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0028_auto_20191027_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='CREATE_TIME',
            field=models.CharField(max_length=200),
        ),
    ]
