# Generated by Django 2.2.6 on 2019-10-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0029_auto_20191027_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dic',
            name='testtime',
        ),
    ]
