from django.db import models
from django.contrib.auth.models import User

class Appeal(models.Model):

    #REPORT_NUM = models.CharField(max_length=200)
    #EVENT_PROPERTY_NAME = models.CharField(max_length=200)
    #EVENT_TYPE_ID = models.CharField(max_length=200)
    #EVENT_TYPE_NAME = models.CharField(max_length=200)
    #EVENT_SRC_NAME = models.CharField(max_length=200)
    #DISTRICT_ID = models.CharField(max_length=200)
    #INTIME_ARCHIVE_NUM = models.CharField(max_length=200)
    #SUB_TYPE_ID = models.CharField(max_length=200)
    #DISTRICT_NAME = models.CharField(max_length=200)
    #COMMUNITY_ID = models.CharField(max_length=200)
    #REC_ID = models.CharField(max_length=200)
    #STREET_ID = models.CharField(max_length=200)
    #OVERTIME_ARCHIVE_NUM = models.CharField(max_length=200)
    #OPERATE_NUM = models.CharField(max_length=200)
    #DISPOSE_UNIT_ID = models.CharField(max_length=200)
    #STREET_NAME = models.CharField(max_length=200)
    #CREATE_TIME = models.DateTimeField(auto_now=False)
    #EVENT_SRC_ID = models.CharField(max_length=200)
    #INTIME_TO_ARCHIVE_NUM = models.CharField(max_length=200)
    #SUB_TYPE_NAME = models.CharField(max_length=200)
    #EVENT_PROPERTY_ID = models.CharField(max_length=200)
    #OCCUR_PLACE = models.CharField(max_length=200)
    #COMMUNITY_NAME = models.CharField(max_length=200)
    #DISPOSE_UNIT_NAME = models.CharField(max_length=200)
    #MAIN_TYPE_NAME = models.CharField(max_length=200)
    #MAIN_TYPE_ID = models.CharField(max_length=200)

    REC_ID = models.IntegerField(primary_key=True)
    REPORT_NUM = models.IntegerField(null=True, blank=True, default=None)
    CREATE_TIME = models.DateTimeField(null=True, blank=True)
    DISTRICT_NAME = models.CharField(max_length=20, blank=True, default='-')
    DISTRICT_ID = models.IntegerField(null=True, blank=True)
    STREET_NAME = models.CharField(max_length=20, blank=True, default='-')
    STREET_ID = models.IntegerField(null=True, blank=True, default=None)
    COMMUNITY_NAME = models.CharField(max_length=20, blank=True, default='-')
    COMMUNITY_ID = models.IntegerField(null=True, blank=True, default=None)
    EVENT_TYPE_NAME = models.CharField(max_length=20, blank=True, default='-')
    EVENT_TYPE_ID = models.IntegerField(null=True, blank=True, default=None)
    MAIN_TYPE_NAME = models.CharField(max_length=20, blank=True, default='-')
    MAIN_TYPE_ID = models.IntegerField(null=True, blank=True, default=None)
    SUB_TYPE_NAME = models.CharField(max_length=40, blank=True, default='-')
    SUB_TYPE_ID = models.IntegerField(null=True, blank=True, default=None)
    DISPOSE_UNIT_NAME = models.CharField(max_length=40, blank=True, default='-')
    DISPOSE_UNIT_ID = models.IntegerField(null=True, blank=True, default=None)
    EVENT_SRC_NAME = models.CharField(max_length=20, blank=True, default='-')
    EVENT_SRC_ID = models.IntegerField(null=True, blank=True, default=None)
    OPERATE_NUM = models.BooleanField(null=True, blank=True, default=None)
    OVERTIME_ARCHIVE_NUM = models.BooleanField(null=True, blank=True, default=None)
    INTIME_TO_ARCHIVE_NUM = models.BooleanField(null=True, blank=True, default=None)
    INTIME_ARCHIVE_NUM = models.BooleanField(null=True, blank=True, default=None)
    EVENT_PROPERTY_ID = models.IntegerField(null=True, blank=True, default=None)
    EVENT_PROPERTY_NAME = models.CharField(max_length=20, blank=True, default='-')
    OCCUR_PLACE = models.CharField(max_length=20, blank=True, default='-')

    def __str__(self):
        return self.REC_ID
